---
- name: Add cloudflared user
  ansible.builtin.user:
    name: cloudflared
    shell: /usr/sbin/nologin
    system: yes
    create_home: no
    state: present

- name: Set ownership of Cloudflared binary
  ansible.builtin.file:
    path: /usr/local/bin/cloudflared
    owner: cloudflared
    group: cloudflared
    mode: '0755'

- name: Create Cloudflared configuration file
  template:
    src: cloudflared_conf.j2
    dest: /etc/default/cloudflared
    owner: cloudflared
    group: cloudflared
    
- name: Create systemd service file for Cloudflared
  template:
    src: cloudflared.service.j2
    dest: /etc/systemd/system/cloudflared.service

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Cloudflared service
  ansible.builtin.systemd:
    name: cloudflared
    state: started
    enabled: yes
