---
- name: Download Cloudflared package
  ansible.builtin.get_url:
    url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
    dest: /tmp/cloudflared-linux-amd64.deb

- name: Install Cloudflared package
  ansible.builtin.apt:
    deb: /tmp/cloudflared-linux-amd64.deb
    update_cache: yes
